name = "regenetron"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-01-28"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"


[vars]
GSHEETS_API_ENDPOINT = "https://sheets.googleapis.com/v4/spreadsheets"
